// const fs = require('fs');
// const path = require('path');
// const {version} = require('./package.json');
//
// const dir = "src/environments";
// const file = "environment.ts";
// const prodFile = "environment.prod.ts";
//
// const content = `${process.env.FIREBASE_DETAILS}`;
//
// fs.access(dir, fs.constants.F_OK, (err) => {
//   if(err) {
//     // Directory doesn't exist
//     console.log('src doesn\'t exist, creating now', process.cwd());
//     // Create /src
//     fs.mkdir(dir, {recursive: true}, (err) => {
//       if (err) throw err;
//     })
//   }
//   // Now write to file
//   try {
//     fs.writeFileSync(dir + "/" + file, content);
//     fs.writeFileSync(dir + "/" + prodFile, content);
//     console.log('Created successfully in', process.cwd());
//     if (fs.existsSync(dir + "/" + file)) {
//       console.log('File is created', path.resolve(dir + "/" + file));
//       const str = fs.readFileSync(dir + "/" + file).toString();
//       console.log(str);
//     }
//   } catch (error) {
//     console.error(error);
//     process.exit(1);
//   }
// })



/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const {version} = require('./package.json');

require('dotenv').config();


function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}


// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

// choose the correct targetPath based on the environment chosen
const targetPath = './src/environments/environment.prod.ts';

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    versionNumber: 'v${version}',
    prefix: '',
    firebase: {
      apiKey: '${process.env.FIREBASE_API_KEY}',
      authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
      databaseURL: '${process.env.FIREBASE_DATABASE_URL}',
      projectId: '${process.env.FIREBASE_PROJECT_ID}',
      storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET}',
      messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
      appId: '${process.env.FIREBASE_APP_ID}',
      measurementId: '${process.env.FIREBASE_MEASUREMENT_ID}'
    },
    globals: {
      team1: 0,
      team2: 1,
      round1: 0,
      round2: 1,
      round3: 2,
    },
    ms: {
      tenant: '${process.env.MS_TENANT}'
    }
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
