import type { IRoom } from '../interfaces/room.interface';

export const wallgrabenData: IRoom[] = [
  {
    id: '1',
    information: {
      number: 'STG.3.1',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '2',
    information: {
      number: 'STG.3.2',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '3',
    information: {
      number: 'STG.3.3',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '4',
    information: {
      number: 'STG.3.4',
      location: 'Stuttgart',
      name: 'Odin',
      icon: 'business_center',
      functional: 'Pausenraum',
    },
    hover: false,
    selected: false,
  },
  {
    id: '5',
    information: {
      number: 'STG.3.5',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '6',
    information: {
      number: 'STG.3.6',
      location: 'Stuttgart',
      name: 'Duro',
      icon: 'meeting_room',
      functional: 'Meetingraum',
    },
    hover: false,
    selected: false,
  },
  {
    id: '7',
    information: {
      number: 'STG.3.7',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '8',
    information: {
      number: 'STG.3.8',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '9',
    information: {
      number: 'STG.3.9',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '10',
    information: {
      number: 'STG.3.10',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '11',
    information: {
      number: 'STG.3.11',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '12',
    information: {
      number: 'STG.3.12',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '13',
    information: {
      number: 'STG.3.13',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '14',
    information: {
      number: 'STG.3.14',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '15',
    information: {
      number: 'STG.3.15',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '16',
    information: {
      number: 'STG.3.16',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '17',
    information: {
      number: 'STG.3.17',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '18',
    information: {
      number: 'STG.3.18',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '19',
    information: {
      number: 'STG.3.19',
      location: 'Stuttgart',
      name: 'Alderaan',
      icon: 'meeting_room',
      functional: 'Meetingraum',
    },
    hover: false,
    selected: false,
  },
  {
    id: '20',
    information: {
      number: 'STG.3.20',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '21',
    information: {
      number: 'STG.3.21',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '22',
    information: {
      number: 'STG.3.22',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '23',
    information: {
      number: 'STG.3.23',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '24',
    information: {
      number: 'STG.3.24',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '25',
    information: {
      number: 'STG.3.25',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '26',
    information: {
      number: 'STG.3.26',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '27',
    information: {
      number: 'STG.3.27',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '28',
    information: {
      number: 'STG.3.28',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '29',
    information: {
      number: 'STG.3.29',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '30',
    information: {
      number: 'STG.3.30',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '31',
    information: {
      number: 'STG.3.31',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '32',
    information: {
      number: 'STG.3.32',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '33',
    information: {
      number: 'STG.3.33',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '34',
    information: {
      number: 'STG.3.34',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '35',
    information: {
      number: 'STG.3.35',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '36',
    information: {
      number: 'STG.3.36',
      location: 'Stuttgart',
      name: 'Bespin',
      icon: 'meeting_room',
      functional: 'Meetingraum',
    },
    hover: false,
    selected: false,
  },
  {
    id: '37',
    information: {
      number: 'STG.3.37',
      location: 'Stuttgart',
      name: 'Büro',
      icon: 'business_center',
    },
    hover: false,
    selected: false,
  },
  {
    id: '38',
    information: {
      number: 'STG.3.38',
      location: 'Stuttgart',
      name: 'Carida',
      icon: 'meeting_room',
      functional: 'Meetingraum',
    },
    hover: false,
    selected: false,
  },
  {
    id: '39',
    information: {
      number: 'WC',
      location: 'Stuttgart',
      name: 'Männer',
      icon: 'wc',
    },
    hover: false,
    selected: false,
  },
  {
    id: '40',
    information: {
      number: 'WC',
      location: 'Stuttgart',
      name: 'Männer',
      icon: 'wc',
    },
    hover: false,
    selected: false,
  },
  {
    id: '41',
    information: {
      number: 'Abstellraum',
      location: 'Stuttgart',
      name: '',
      icon: 'checkroom',
    },
    hover: false,
    selected: false,
  },
  {
    id: '42',
    information: {
      number: 'WC',
      location: 'Stuttgart',
      name: 'Frauen',
      icon: 'wc',
    },
    hover: false,
    selected: false,
  },
  {
    id: '43',
    information: {
      number: 'Küche',
      location: 'Stuttgart',
      name: 'Hier gibts leckeren Caffee',
      icon: 'coffee_maker',
    },
    hover: false,
    selected: false,
  },
  {
    id: '44',
    information: {
      number: 'WC',
      location: 'Stuttgart',
      name: 'Frauen',
      icon: 'wc',
    },
    hover: false,
    selected: false,
  },
  {
    id: '45',
    information: {
      number: 'Abstellraum',
      location: 'Stuttgart',
      name: '',
      icon: 'checkroom',
    },
    hover: false,
    selected: false,
  },
  {
    id: '46',
    information: {
      number: 'Küche',
      location: 'Stuttgart',
      name: 'Hier gibts leckeren Caffee',
      icon: 'coffee_maker',
    },
    hover: false,
    selected: false,
  },
];
